/* guide.js — step-by-step build guide (renders with the live model so dimensions always match the parameters) */
(function (root) {
'use strict';
const CAD = root.CAD;
const N = Math.round;

function guideSteps(M) {
  const L = M.L, d = id => M.defs.get(id), q = id => d(id).qty;
  const Lr = L.Wc - 88, Le = L.Dc - 88, zc = L.Hl - 35;
  const tMark = ['Tape & steel rule', 'Marking knife', 'Combination square', 'Mortise gauge'], tChop = ['Bench chisels 6 · 12 mm', 'Mallet', 'Bench hook & clamps'], tSaw = ['Tenon saw', 'Shoulder plane', 'Router plane (optional)'];
  const S = [];
  const add = o => { o.n = S.length + 1; S.push(o); return o; };
  add({ kind: 'hero', phase: 'Welcome', title: 'Walnut sideboard with stone top', text: [
    `Finished size <b>${L.W} × ${L.D} × ${L.H} mm</b>: four legs on an H-stretcher base, a carcass with two drawers and two sliding slatted doors, and a ${L.W} mm stone top.`,
    `<b>No hardware at all.</b> Every connection is glued wood joinery. You will cut six joint families: pegged mortise &amp; tenon, housed dado with tongue, floating-panel grooves, box joints, slat tenons and wooden stone keys.`,
    `Build order: base frame → carcass → drawers → sliding doors → top. <b>Dry-fit every joint before glue.</b>`,
    `<b>How to read the pictures:</b> <span style="color:#e86a00">orange parts</span> are new in this step; <span style="color:#e86a00">orange boxes</span> inside a part are wood to remove (mortises, dados, grooves); <span style="color:#18a34a">green boxes</span> are tenons and tongues you leave standing.`], tools: [], tip: 'Cut a spare of every joint type in scrap first. The 20 minutes it costs saves a ruined leg.', chk: 'Everything in this guide is dimensioned from the same 3D model you can inspect, section and export.' });
  add({ kind: 'flat', phase: 'Welcome', title: 'Parts overview', text: [`<b>${M.defs.size} part types, ${M.insts.length} pieces.</b> Each tile is labelled with its name and quantity; part IDs match the cut list on the next page.`, `Legs come in a <b>mirror pair</b> (type A ×2, type B ×2) because the stretcher mortise sits on a different face.`, `The back panel and drawer bottoms are 6 mm veneered ply; everything else is solid walnut except the marble top.`, `Pegs and stone keys are small offcuts of walnut with the end grain showing.`], tools: [], tip: 'Label every blank in pencil with its part name and orientation arrow the moment you cut it.' });
  add({ kind: 'cutlist', phase: 'Prepare', title: 'Cut list & milling', text: [] });
  add({ kind: 'text', phase: 'Prepare', title: 'Tools & materials', text: [
    '<b>Stock:</b> kiln-dried American walnut 8/4 (legs, ' + N(L.Hl / 10) + ' cm blanks), 5/4 (panels, rails, drawer fronts), 4/4 (everything else); one 6 mm walnut-veneered ply sheet ≥ 1.4 × 0.4 m; one 20 mm marble slab with four blind sockets (ask the fabricator).',
    '<b>Marking:</b> tape measure, steel rule, marking knife, combination square, mortise gauge, marking gauge, pencil.',
    '<b>Cutting:</b> table saw or tenon saw, dozuki saw, bench chisels 6 / 8 / 12 / 25 mm, mallet, shoulder plane, router with straight bits 6, 8, 12 and 18 mm (or router plane + tenon saw), 6 mm drill bit for peg holes.',
    '<b>Gluing &amp; finishing:</b> PVA wood glue, ≥ 8 clamps with cauls, wax or hard-wax oil, 180–320 grit paper, flexible stone adhesive or silicone, felt pads. <b>No screws, nails, brackets, runners, hinges or handles are used.</b>'], tools: [], tip: 'Let stock acclimatise indoors for a week and mill it oversize first, then to final size just before cutting joints.' });
  add({ kind: 'subset', phase: 'Frame joinery', title: 'Anatomy of the main frame joint', show: [{ def: 'leg_A', idx: 1, ex: [0, 0, 0] }, { def: 'apron_end', idx: 1, ex: [0, 150, 0] }, { def: 'stretcher_end', idx: 1, ex: [0, 150, -40] }, { def: 'peg22', idx: 2, ex: [-110, 0, 0] }, { def: 'peg30', idx: 1, ex: [-110, 0, 0] }], tags: ['mortiseB', 'mortiseS', 'tenon'], dir: [.95, .75, .5], zoom: 520,
    text: [`Every frame joint is a <b>blind mortise &amp; tenon</b>: tenon <b>8 mm</b> thick (⅓ of the 22 mm rail), <b>24 mm</b> long (55 % of the 44 mm leg), with shoulders on all four sides.`, `The mortise stops <b>15 mm below the leg shoulder</b> so the leg can never split out at the top.`, `Rails sit <b>4 mm back</b> from the leg faces for a clean shadow line.`, `A <b>6 × 6 mm square peg</b> locks each joint. When you drill the tenon, offset its hole <b>1.5 mm toward the shoulder</b> (draw-boring): the peg pulls the joint tight without clamps.`], tools: [], tip: 'Orange pieces here show how parts slide apart. In the build they glue together.', chk: 'Tenon should enter the mortise with light hand pressure and no rocking.' });
  add({ kind: 'part', phase: 'Frame joinery', title: 'Mark out the legs', focus: ['leg_A'], tags: ['mortiseA', 'mortiseB', 'mortiseS', 'pegA', 'pegB', 'pegS', 'tenonTop'], dir: [.85, .8, .6], zoom: 'first', parts: [{ def: 'leg_A', qty: q('leg_A') }, { def: 'leg_B', qty: q('leg_B') }], text: [
    `Plane four legs to <b>44 × 44 × ${L.Hl + 20}</b> mm (20 mm extra on top for the tenon and trimming). Choose the best two adjacent faces as the outside faces.`, `Pair them: <b>two type A</b> (front-left and back-right) and <b>two type B</b> (front-right and back-left). Type B has its stretcher mortise on the other inside face, so mark it as a mirror image.`, `With a square and knife, mark the <b>shoulder line</b> ${L.Hl} mm from the foot. Everything is measured from the outside faces.`, `Set the mortise gauge to <b>8 mm</b>, 11 mm from the outside face; mark mortise A and B (24 × 40 mm each, top edge 15 mm below the shoulder). Mark the stretcher mortise (24 × 20, thickness 10 mm) centred at ${L.zs} mm.`], tools: tMark, tip: 'Mark both leg types at the same time from one story stick so heights match to the millimetre.', chk: 'Hold type A and B back-to-back: the marks should mirror each other.' });
  add({ kind: 'part', phase: 'Frame joinery', title: 'Chop the rail mortises (A and B)', focus: ['leg_A'], tags: ['mortiseA', 'mortiseB'], dir: [.85, .8, .6], zoom: 'first', parts: [{ def: 'leg_A', qty: q('leg_A') + q('leg_B') }], text: [`Clamp the leg on the bench. Drill out most of the waste with a <b>8 mm brad-point bit</b> stopped at <b>24 mm</b> (tape flag on the bit).`, `Chop the remainder with the 8 mm chisel, working from the centre toward each end; keep the chisel vertical and leave ~1 mm to the knife line.`, `Pare the walls and end walls to the line, flat and square. Mortise A (24 × 8 × 40) and B are the same size, on the two inside faces.`, `<b>Cheek rule:</b> the wall on the outside is 11 mm, more than the 8 mm tenon, so it will not blow out.`], tools: tChop, tip: 'Cut mortise B first, then A: the two meet inside the leg corner but never touch because their tenons stop 4 mm short of each other.', chk: 'Slide the shank of an 8 mm drill bit in: it should sit square to the face all the way down.' });
  add({ kind: 'part', phase: 'Frame joinery', title: 'Stretcher mortise and peg holes', focus: ['leg_A'], tags: ['mortiseS', 'pegA', 'pegB', 'pegS'], dir: [.85, .8, .45], zoom: 'first', parts: [{ def: 'leg_A', qty: q('leg_A') + q('leg_B') }], text: [`Chop the <b>stretcher mortise</b> 24 mm deep, 10 mm thick, 20 mm tall on the inside face (type A: toward the other leg of the same end; type B: the other face).`, `Chisel or drill the <b>peg holes</b> 6 × 6 mm: two apron holes 22 mm deep from each outside face, and one stretcher hole 30 mm deep.`, `Square holes: drive a sharp 6 mm chisel across the grain, then pare. You may drill Ø6 round holes and use round pegs instead.`, `Break every edge lightly with 240-grit paper.`], tools: ['6 mm chisel', 'Drill + 6 mm brad-point', 'Mallet'], tip: 'Peg holes go through the leg cheek and stop inside the far wall: never through the leg.', chk: 'Blind holes: the peg stands flush with the outside face when fully driven.' });
  add({ kind: 'part', phase: 'Frame joinery', title: 'Cut the top tenon on every leg', focus: ['leg_A'], tags: ['tenonTop'], dir: [.85, -.8, .7], zoom: 'first', parts: [{ def: 'leg_A', qty: q('leg_A') + q('leg_B') }], text: [`Square off the top to the <b>${L.Hl} mm shoulder</b>. Mark a <b>24 × 24 mm tenon, 14 mm tall</b>, centred, leaving a 10 mm shoulder on all sides.`, `Saw the cheeks, then the shoulders, and pare them clean with the shoulder plane.`, `These four tenons locate the carcass floor and hold it in place with glue.`], tools: tSaw, tip: 'Cut the top tenons after the mortises so the legs stay long and easy to hold while chopping.', chk: 'Tenon should push into a test mortise in scrap with a gentle tap.' });
  add({ kind: 'part', phase: 'Frame joinery', title: 'Cut the apron-rail tenons', focus: ['apron_long', 'apron_end'], tags: ['tenon', 'pegHole'], dir: [.7, -.9, .6], zoom: 'first', parts: [{ def: 'apron_long', qty: q('apron_long') }, { def: 'apron_end', qty: q('apron_end') }], text: [`Rails: <b>22 × 60 mm</b>; front/back ${Lr + 48} mm long, end rails ${Le + 48} mm long (finished sizes include 24 mm tenons).`, `Gauge the tenon <b>8 mm thick</b>, 7 mm from the inside face of the rail. Mark it <b>40 mm tall</b>: 5 mm shoulder below, 15 mm above.`, `Saw the cheeks to the line, then the shoulders. Pare cheeks flat; trim until it enters the mortise with light hand pressure.`, `Drill/chisel the tenon peg hole 12 mm from the shoulder. <b>For draw-boring, shift it 1.5 mm toward the shoulder from the leg hole centre.</b>`], tools: tSaw.concat(['Mortise gauge']), tip: 'Cut all eight tenons from one set-up on the saw so they are identical.', chk: 'Test each tenon in its own leg; mark the pair with a matching number.' });
  add({ kind: 'part', phase: 'Frame joinery', title: 'Stretcher tenons and the long-stretcher mortise', focus: ['stretcher_end', 'stretcher_long'], tags: ['tenon', 'pegHole', 'mortiseL'], dir: [.7, -.9, .7], zoom: 'first', parts: [{ def: 'stretcher_end', qty: q('stretcher_end') }, { def: 'stretcher_long', qty: q('stretcher_long') }], text: [`End stretchers: <b>30 × 30 × ${Le + 48}</b> mm. Tenons <b>10 mm thick, 20 tall, 24 long</b>, centred; peg hole 12 mm from each shoulder.`, `Chop the <b>central mortise</b> (22 deep × 10 wide × 20 tall) on the inside face of each end stretcher, exactly at mid-length.`, `Long stretcher: <b>30 × 30 × ${L.Wc - 74 + 44}</b> mm with a <b>10 × 20 × 22 mm</b> tenon at each end.`, `This is the H of the H-stretcher: two ends joined by the long one at mid-depth.`], tools: tSaw.concat(['Chisels']), tip: 'Cut both end stretchers together, clamped face-to-face, for matching mortises.', chk: 'Test-fit the long stretcher between the two end stretchers: no gaps at the shoulders.' });
  add({ kind: 'asm', phase: 'Frame assembly', title: 'Glue the two end frames', asm: 0, dir: [.75, -.85, .65], text: [`Dry-fit first: each end frame is <b>two legs + one end rail + one end stretcher</b>.`, `Brush glue on the mortise walls only (not the tenon, so squeeze-out stays outside). Push all tenons home.`, `Clamp across the shoulders. Check both frames for twist by sighting across them; adjust clamps until flat.`, `Check the diagonals of each end frame: they must match within 1 mm.`], tools: ['PVA glue', 'Clamps ×4', 'Square', 'Damp cloth'], tip: 'Leave the pegs out for now. Glue the end frames as a mirror pair on a flat surface.', chk: 'Wipe squeeze-out off with a damp rag before it skins.' });
  add({ kind: 'asm', phase: 'Frame assembly', title: 'Join the end frames', asm: 1, dir: [.7, -.9, .6], text: [`Stand the two end frames up and slide in the <b>front and back aprons</b> and the <b>long stretcher</b> together.`, `Glue every mortise. Seat the long stretcher into the end stretchers first, then the aprons.`, `Clamp across the width at the apron and stretcher heights; check the base sits on a flat floor without rocking.`], tools: ['PVA glue', 'Long clamps ×3', 'Winding sticks'], tip: 'Measure diagonals across the top of the legs: equal diagonals = square frame.', chk: 'Frame sits flat; the four top shoulders are level (tape-measure from a table).' });
  add({ kind: 'asm', phase: 'Frame assembly', title: 'Drive the draw-bore pegs', asm: 2, detail: 'first', exf: 1.1, dir: [.8, -.9, .5], text: [`Taper the tip of each <b>6 × 6 mm</b> peg with a knife (a short wedge point).`, `Drive the apron pegs (22 mm) and stretcher pegs (30 mm) from the <b>outside faces</b>, tapping with the mallet. Because the tenon hole is offset, each peg draws the shoulder tight.`, `Leave pegs <b>1 mm proud</b>; trim and pare flush after the glue is dry.`, `<b>12 pegs total</b>: 8 at the aprons, 4 at the stretchers.`], tools: ['Mallet', 'Knife', 'Flush saw', 'Chisel'], tip: 'Drive pegs with the grain of the leg running the same way as the peg grain to avoid splitting.', chk: 'No peg should bend or crack. If it does, enlarge the offset less next time (1.5 mm max).' });
  add({ kind: 'part', phase: 'Carcass joinery', title: 'Bottom panel: mortises, dados and tracks', focus: ['panel_bottom'], tags: ['mortiseTop', 'dadoEnd', 'dadoDiv', 'grooveBack', 'track'], dir: [.4, -.95, .85], zoom: 520, parts: [{ def: 'panel_bottom', qty: 1 }], text: [`Glue up boards to <b>${L.Wc} × ${L.Dc} × 22 mm</b>. Flatten and sand the top face.`, `Chop four <b>24 × 24 × 14 mm</b> blind mortises in the underside for the leg tenons.`, `Router (or plane) <b>18 × 8 mm dados</b> on the top face for the end panels (at 8 mm from each end) and the divider. All stop 14 mm from the front edge.`, `Rout the <b>6 mm back groove</b> (6 deep) 20 mm from the rear edge and the two <b>18 × 5 mm door tracks</b> from the divider to the right end panel.`], tools: ['Router + 6, 18 mm bits', 'Straight edge', 'Chisels', 'Square'], tip: 'Clamp a straight-edge fence to guide the router for every dado: set the fence once for each width.', chk: 'Dry-fit an end-panel tongue in its dado: snug, not tight.' });
  add({ kind: 'part', phase: 'Carcass joinery', title: 'Top panel: dados, tracks and key mortises', focus: ['panel_top'], tags: ['dadoEnd', 'dadoDiv', 'grooveBack', 'track', 'mortiseKey'], dir: [.4, .95, -.55], zoom: 520, parts: [{ def: 'panel_top', qty: 1 }], text: [`Same size as the bottom: <b>${L.Wc} × ${L.Dc} × 22 mm</b>. Work on the <b>underside</b>: the dados mirror the bottom panel (8 mm deep).`, `Door tracks are <b>12 mm deep</b> here (5 mm in the bottom): this extra depth lets you lift each door in, then drop it down.`, `Rout the 6 mm back groove (6 deep).`, `On the <b>top face</b> chop four <b>12 × 12 × 8 mm</b> key mortises. Keep them away from the door tracks.`], tools: ['Router', 'Chisels', 'Square'], tip: 'Rout the 12 mm tracks in two passes of 6 mm.', chk: 'The 2 mm web between track and key mortise must stay intact.' });
  add({ kind: 'part', phase: 'Carcass joinery', title: 'End panels', focus: ['endpanel_L', 'endpanel_R'], tags: ['tongue', 'grooveBack', 'dadoRail', 'dadoStrip'], dir: [.8, .9, .6], zoom: 'first', parts: [{ def: 'endpanel_L', qty: 1 }, { def: 'endpanel_R', qty: 1 }], text: [`Two panels <b>18 × ${L.Dc} × ${L.Hc - 44}</b> mm. Cut an <b>8 mm tongue</b> top and bottom (stopped 14 mm from the front).`, `Both panels: <b>6 × 6 mm back groove</b> on the inside face, 20 mm from the rear edge.`, `<b>Left panel only</b> (drawer side): one <b>20 × 6 mm dado</b> for the drawer rail and two <b>10 × 4 mm stopped dados</b> for the drawer guide strips.`, `Mark L and R on the inside faces: the grooves are a mirror pair.`], tools: ['Router table or saw', 'Router', 'Chisels'], tip: 'Cut the tongues first so you can use the same fence setting for both panels.', chk: 'Place L and R face to face: their back grooves should line up.' });
  add({ kind: 'part', phase: 'Carcass joinery', title: 'Divider, drawer rail and guide strips', focus: ['divider', 'drawer_rail', 'guide_strip'], tags: ['tongue', 'dadoRail', 'dadoStrip', 'embed'], dir: [.8, .9, .7], zoom: 'first', parts: [{ def: 'divider', qty: 1 }, { def: 'drawer_rail', qty: 1 }, { def: 'guide_strip', qty: q('guide_strip') }], text: [`<b>Divider:</b> 18 mm thick, tongued top and bottom like the end panels. On its left face cut the same <b>rail dado (20 × 6)</b> and two <b>strip dados (10 × 4)</b>.`, `<b>Drawer rail:</b> 20 mm tall; a <b>6 mm long tongue</b> on each end (stopped 10 mm from the front) fits the rail dados.`, `<b>Guide strips</b> (×4): 10 × 10 mm. The first 4 mm of the thickness glues into the dado; the other 6 mm slides in the drawer groove. Wax them.`], tools: ['Router', 'Plane', 'Wax'], tip: 'Make the four strips from one length of straight-grain stock and crosscut after planing.', chk: 'The strip should seat in its dado with finger pressure and protrude exactly 6 mm.' });
  add({ kind: 'part', phase: 'Carcass joinery', title: 'Floating back panel', focus: ['back_panel'], tags: ['notch'], dir: [.4, -.9, .6], zoom: 'first', parts: [{ def: 'back_panel', qty: 1 }], text: [`Cut the 6 mm ply to <b>${L.xR - L.xL + 12} × ${L.Hc - 32} mm</b>. It floats in the 6 mm grooves of the top, bottom and end panels.`, `<b>Notch the four corners 6 × 6 mm</b> so the panel clears the dado shoulders.`, `<b>Never glue it.</b> A loose panel lets the solid wood move with the seasons.`, `Finish the inside face before assembly.`], tools: ['Table saw', 'Fine saw', 'Sandpaper'], tip: 'Sand a 1 mm chamfer on the edges so it slides easily into the grooves.', chk: 'It slips into the groove with 0.5 mm of play at each end.' });
  add({ kind: 'asm', phase: 'Carcass assembly', title: 'Set the carcass floor on the base', asm: 3, dir: [.7, -.95, .8], text: [`Glue only the <b>four leg tenons</b> and set the bottom panel onto them.`, `Keep the panel flush with the outside faces of the legs and 2 mm back from the front line of the aprons.`, `Weight the panel overnight with sandbags; no clamps needed.`], tools: ['PVA glue', 'Sandbags'], tip: 'The aprons carry the load; the tenons just locate and hold.', chk: 'Panel overhangs the legs by 0: the legs are flush with the carcass edges.' });
  add({ kind: 'asm', phase: 'Carcass assembly', title: 'Stand the bay walls', asm: 4, dir: [.65, -.9, .85], text: [`Dry-fit the order: <b>glue the drawer rail into the left end panel and divider first</b>, with the guide strips glued in their dados.`, `Spread glue in the stopped dados of the bottom panel and stand the <b>left end panel, divider and right end panel</b> upright.`, `Check the <b>drawer opening is square</b> and exactly ${L.Wbay} mm wide (a spacer stick helps).`], tools: ['PVA glue', 'Clamps', 'Spacer stick', 'Square'], tip: 'Keep the strip dado walls free of glue squeeze-out; wax them after.', chk: 'Drawer rail is level; strips are parallel to the carcass sides.' });
  add({ kind: 'asm', phase: 'Carcass assembly', title: 'Slide in the back panel', asm: 5, dir: [.5, 1, .8], text: [`Slide the floating back panel down the end-panel grooves and into the bottom groove from the rear.`, `Do not glue it. The panel must stay free to move.`, `Check it is straight; the rear 14 mm lip of the panels protects the panel edges.`], tools: ['Hands only'], tip: 'Wax the groove walls so it slides without sticking.' });
  add({ kind: 'asm', phase: 'Carcass assembly', title: 'Fit the top panel', asm: 6, dir: [.65, -.9, .7], text: [`Spread glue in the end-panel and divider dados in the top panel, then lower it over the tongues.`, `Clamp across the carcass at the front and back; check square with diagonals.`, `Wipe off squeeze-out inside the drawer and door bays now. It is almost impossible to reach later.`], tools: ['PVA glue', 'Clamps ×6', 'Damp cloth'], tip: 'Pre-assemble dry with the clamps to find any binding before applying glue.', chk: 'Door tracks above and below are in line when you sight along them.' });
  add({ kind: 'part', phase: 'Drawers', title: 'Drawer: box joints', focus: ['drawer_front', 'drawer_side_L', 'drawer_side_R'], tags: ['finger', 'fingerSlot'], dir: [.7, -.85, .8], zoom: 'first', parts: [{ def: 'drawer_front', qty: q('drawer_front') }, { def: 'drawer_side_L', qty: q('drawer_side_L') }, { def: 'drawer_side_R', qty: q('drawer_side_R') }], text: [`Each drawer: front <b>22 × 100 × ${L.Wdr}</b> mm, sides <b>12 × 100 × ${L.Ld}</b> mm. Front/side joint is a <b>5-finger box joint, 20 mm fingers</b>.`, `Mark the side's front end with the finger grid; the side gets notches at 0-2-4, the front's ends get fingers at 0-2-4.`, `Cut on the table saw with a box-joint jig, or by hand: knife, saw the walls, chop the waste with a 12 mm chisel.`, `Cut the rear joints between sides and back the same way, but only above the bottom groove (from 14 mm up).`], tools: ['Table saw + jig, or', 'dozuki saw', 'Chisels 12 · 20 mm', 'Marking knife'], tip: 'Make the first joint 0.1 mm tight and plane to fit; a loose box joint cannot be fixed.', chk: 'Fingers should push in under hand pressure and finish flush on both faces.' });
  add({ kind: 'part', phase: 'Drawers', title: 'Drawer: grooves and finger pull', focus: ['drawer_front', 'drawer_side_L'], tags: ['grooveBottom', 'pull', 'guideGroove'], dir: [.7, .85, .7], zoom: 'first', parts: [{ def: 'drawer_front', qty: q('drawer_front') }, { def: 'drawer_side_L', qty: q('drawer_side_L') }, { def: 'drawer_back', qty: q('drawer_back') }, { def: 'drawer_bottom', qty: q('drawer_bottom') }], text: [`Router a <b>6 mm groove, 8 mm deep</b>, 8 mm up from the bottom edge across the inside of the front, and <b>5 mm deep</b> along the inside of each side (open at the rear so the bottom slides in).`, `On the outside of each side rout the <b>12 mm tall × 5.5 mm deep runner groove</b> at mid-height, from 22 mm behind the front to the rear end.`, `On the front face, cut the <b>finger pull 120 × 20 mm, 12 mm deep</b>, near the top edge.`, `The drawer bottom is 6 mm ply, loose in the grooves.`], tools: ['Router + 6, 12 mm bits', 'Chisels'], tip: 'Rout the runner groove before gluing the drawer. It is a thousand times easier.', chk: 'A guide strip dropped in the runner groove has about 1 mm of play.' });
  add({ kind: 'subset', phase: 'Drawers', title: 'Glue up a drawer', show: [{ def: 'drawer_front', idx: 1, ex: [0, -160, 0] }, { def: 'drawer_side_L', idx: 1, ex: [-150, 0, 0] }, { def: 'drawer_side_R', idx: 1, ex: [150, 0, 0] }, { def: 'drawer_back', idx: 1, ex: [0, 170, 40] }, { def: 'drawer_bottom', idx: 1, ex: [0, 120, -60] }], dir: [.6, -.9, .75], zoom: 700, text: [`Dry-fit: slide the bottom into the front groove and the two side grooves from the rear, then add the back.`, `Glue <b>only the box joints</b>. The bottom stays loose.`, `Clamp across the front and back; check the drawer is square by diagonals (equal within 1 mm).`, `Let it set flat on a bench.`], tools: ['PVA glue', 'Clamps ×4', 'Square'], tip: 'Do not glue the bottom: it needs to float.', chk: 'Drawer sits flat on the bench with no rock.' });
  add({ kind: 'asm', phase: 'Drawers', title: 'Fit the drawers', asm: 7, dir: [.55, -1, .55], text: [`Wax the guide strips and the drawer runner grooves with paraffin or candle wax.`, `Slide each drawer in from the front: the groove picks up the strip.`, `Plane the sides until there is a <b>1.5 mm gap each side</b> and 1.5 mm above and below.`], tools: ['Wax', 'Block plane'], tip: 'Mark which drawer goes where (L-lower, U-upper) on the underside.', chk: 'Drawer front is flush with the carcass front, within 1 mm.' });
  add({ kind: 'part', phase: 'Sliding doors', title: 'Door stiles and rails', focus: ['door_stile', 'door_rail'], tags: ['mortiseRail', 'tenon', 'mortiseSlat'], dir: [.75, -.85, .8], zoom: 'first', parts: [{ def: 'door_stile', qty: q('door_stile') }, { def: 'door_rail', qty: q('door_rail') }], text: [`Each door is <b>${L.Wd} × ${L.Hd} × 16 mm</b>: two <b>24 × 16</b> stiles and two <b>30 × 16</b> rails.`, `Chop <b>18 × 5 × 20 mm</b> mortises at both ends of each stile; saw matching tenons on the rails.`, `On the rails cut <b>${L.nSlat} slat mortises 8 × 5 × 12 mm</b> at ${fx(L.slat + L.gap)} mm pitch (gap ${fx(L.gap)} mm).`, `Door height ${L.Hd} mm = opening + 7 mm: that is what lets you lift it into the deep top track and drop it into the bottom one.`], tools: ['Router or chisels', 'Mortise gauge', 'Tenon saw'], tip: 'Use a story stick for the slat spacing and mark both rails together.', chk: 'Both rails must have identical mortise positions.' });
  add({ kind: 'part', phase: 'Sliding doors', title: 'Slats', focus: ['door_slat'], tags: ['tenon'], dir: [.9, -.8, .7], zoom: 'first', parts: [{ def: 'door_slat', qty: q('door_slat') }], text: [`Plane ${q('door_slat')} slats to <b>12 × 16 mm</b>, ${d('door_slat').size.slice().sort((a, b) => b - a)[0]} mm long including tenons.`, `Cut an <b>8 × 5 × 12 mm tenon</b> on both ends. A stop block on the saw makes every slat identical.`, `Ease the long edges with 240-grit; a very slight chamfer catches the light.`], tools: ['Table saw + stop block', 'Plane', 'Sandpaper'], tip: 'Cut one spare slat per door.', chk: 'Shoulder-to-shoulder length must be identical: check with a stop block.' });
  add({ kind: 'subset', phase: 'Sliding doors', title: 'Glue up a door', show: [{ def: 'door_stile', idx: 1, ex: [-120, 0, 0] }, { def: 'door_stile', idx: 2, ex: [120, 0, 0] }, { def: 'door_rail', idx: 1, ex: [0, 0, -100] }, { def: 'door_rail', idx: 2, ex: [0, 0, 100] }].concat(Array.from({ length: Math.min(L.nSlat, 16) }, (_, i) => ({ def: 'door_slat', idx: i + 1, ex: [0, 0, 0] }))), dir: [.4, -1, .45], zoom: 640, text: [`Dry-fit the slats into the bottom rail, then add the top rail.`, `Glue the slat tenons into the rails first, then add the stiles. Clamp across the rails only.`, `Check square and flat on a bench; wipe any squeeze-out.`, `Make two doors: they are identical.`], tools: ['PVA glue', 'Clamps ×3', 'Square'], tip: 'Use a spacer strip between slats during glue-up.', chk: 'Slats parallel and all spaced equally.' });
  add({ kind: 'asm', phase: 'Sliding doors', title: 'Install the doors', asm: 8, exf: .9, dir: [1, -.75, .55], text: [`Wax both tracks and the top and bottom edges of the doors.`, `<b>Lift</b> the door up into the 12 mm top track until the bottom clears, <b>swing</b> the bottom in over its 5 mm track, then <b>drop</b> it down.`, `Door A (left) in the front track, door B (right) in the rear track. They pass each other with a 6 mm web between them.`, `Plane the stile edge until the door slides freely but without rattling.`], tools: ['Wax', 'Plane'], tip: 'If the door binds, wax first. Then plane no more than 0.2 mm at a time.', chk: 'Each door slides the full opening without touching the other door.' });
  add({ kind: 'part', phase: 'Stone top', title: 'Stone keys and sockets', focus: ['stone_key', 'marble'], tags: ['socketKey'], dir: [.6, -.9, -.35], zoom: 'first', parts: [{ def: 'marble', qty: 1 }, { def: 'stone_key', qty: q('stone_key') }], text: [`The stone has four <b>12 × 12 × 6 mm blind sockets</b> in its underside; the fabricator drills them from your drawing.`, `Each <b>walnut key</b> (12 × 12 × 14 mm) sits 8 mm in the top-panel mortise and 6 mm in the stone socket.`, `Glue the keys <b>only into the wood mortises</b>. The stone sockets get a drop of silicone so the stone can lift off for service.`], tools: ['Chisel', 'Mallet', 'Silicone'], tip: 'Dry-fit the stone first; never test-fit with glue on.', chk: 'Stone sits on the top panel without rocking; sockets line up.' });
  add({ kind: 'asm', phase: 'Stone top', title: 'Fit the stone keys', asm: 9, detail: 'first', exf: .8, dir: [.6, -.9, .8], text: [`Glue the four keys into the top-panel mortises, end grain up.`, `Wipe off any glue; let it cure 30 minutes.`], tools: ['PVA glue'], tip: 'Mark the key positions on the underside of the stone with tape to find them quickly.' });
  add({ kind: 'asm', phase: 'Stone top', title: 'Bed the marble top', asm: 10, dir: [.65, -.9, .7], text: [`Run a thin zig-zag of flexible stone adhesive on the top panel (not near the edges).`, `Lower the stone vertically onto the keys with two people; check the 10 mm overhang is even.`, `Weight with sandbags 24 h.`], tools: ['Stone adhesive', 'Two people'], tip: 'Protect the stone edge with a towel while lifting.', chk: 'Overhang: 10 mm all round (check at four points).' });
  add({ kind: 'hero', phase: 'Finish', title: 'Finish and enjoy', final: true, text: [`Sand to 240 grit, remove dust, then apply <b>two coats of hard-wax oil</b>. Do not oil the stone.`, `Fit <b>felt pads</b> under the feet if the floor needs them.`, `Check once a year: wax the door tracks and drawer strips.`, `<b>You built it with no hardware.</b>`], tools: [], tip: 'Give the first coat of oil 24 hours before the second.' });
  return S;
  function fx(v) { return (+v).toFixed(1).replace(/\.0$/, ''); }
}
CAD.guideSteps = guideSteps;

CAD.makeGuide = function (ctx) {
  const T = ctx.T, S = ctx.S, V = (x, y, z) => new T.Vector3(x, y, z), $ = s => document.querySelector(s);
  const gs = new T.Scene(); gs.environment = ctx.scene.environment; gs.add(new T.HemisphereLight(0xffffff, 0x8a8478, .62)); const sun = new T.DirectionalLight(0xfff4e6, 1.0); sun.position.set(-1400, -2200, 2600); gs.add(sun); const f2 = new T.DirectionalLight(0xdbe6ff, .35); f2.position.set(2000, 1200, 900); gs.add(f2);
  const cam = new T.PerspectiveCamera(28, 1, 5, 40000); cam.up.set(0, 0, 1); const lineMat = new T.LineBasicMaterial({ color: 0x24160d, transparent: true, opacity: .42 });
  let steps = null, pages = null, cur = 0, thumbs = {};
  const clear = () => { while (gs.children.length > 3) gs.remove(gs.children[gs.children.length - 1]); };
  function orientM(size) { const idx = [0, 1, 2].sort((a, b) => size[b] - size[a]), m = new T.Matrix4(), r = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]; idx.forEach((ax, i) => r[i][ax] = 1); m.set(...r[0], 0, ...r[1], 0, ...r[2], 0, 0, 0, 0, 1); if (m.determinant() < 0) { r[2] = r[2].map(v => -v); m.set(...r[0], 0, ...r[1], 0, ...r[2], 0, 0, 0, 0, 1); } return m; }
  function addInst(def, matrix, kind, parent) {
    const g = ctx.geomOf(def), mat = ctx.getMat(kind || 'real', def.solid.mat), me = new T.Mesh(g, mat); me.matrixAutoUpdate = false; me.matrix.copy(matrix); const ln = new T.LineSegments(def.edgeGeom, lineMat); ln.matrixAutoUpdate = false; ln.matrix.copy(matrix); (parent || gs).add(me, ln); return me;
  }
  function featBoxes(def, matrix, tags, onlyNear) {
    const out = []; def.solid.feat.forEach(f => { if (!tags.includes(f.tag)) return; const b = f.box, g = f.kind === 'cut' ? 0 : .35, w = [b[3] - b[0] + 2 * g, b[4] - b[1] + 2 * g, b[5] - b[2] + 2 * g];
      const m = new T.Mesh(new T.BoxGeometry(w[0], w[1], w[2]), new T.MeshBasicMaterial({ color: f.kind === 'cut' ? 0xff7a00 : 0x16a34a, transparent: true, opacity: f.kind === 'cut' ? .62 : .5, depthWrite: false, polygonOffset: true, polygonOffsetFactor: -2, polygonOffsetUnits: -2 }));
      m.position.set((b[0] + b[3]) / 2, (b[1] + b[4]) / 2, (b[2] + b[5]) / 2); const e = new T.LineSegments(new T.EdgesGeometry(m.geometry), new T.LineBasicMaterial({ color: f.kind === 'cut' ? 0xb34700 : 0x0b6b2e })); e.position.copy(m.position); const grp = new T.Group(); grp.add(m, e); grp.applyMatrix4(matrix); gs.add(grp); out.push({ f, c: V(m.position.x, m.position.y, m.position.z).applyMatrix4(matrix), size: w, box: b, matrix }); }); return out;
  }
  const SZ3 = [1000, 1150], SZF = [1400, 1230], SZD = [680, 540];
  function frame(cam_, box, dir, fill, aspect) {
    fill = fill || .86; cam_.aspect = aspect; cam_.updateProjectionMatrix(); const dv = V(...dir).normalize(), c = box.getCenter(V(0, 0, 0)), r = Math.max(40, box.getSize(V(0, 0, 0)).length() / 2);
    const cs = []; for (let i = 0; i < 8; i++) cs.push(V(i & 1 ? box.max.x : box.min.x, i & 2 ? box.max.y : box.min.y, i & 4 ? box.max.z : box.min.z));
    const solve = (tg) => { let lo = r * .3, hi = r * 40; for (let k = 0; k < 40; k++) { const d = (lo + hi) / 2; cam_.position.copy(tg).addScaledVector(dv, d); cam_.up.set(0, 0, 1); cam_.lookAt(tg); cam_.updateMatrixWorld(); let m = 0; cs.forEach(p => { const q = p.clone().project(cam_); m = Math.max(m, Math.abs(q.x), Math.abs(q.y)); }); if (m > fill) lo = d; else hi = d; } return hi; };
    let tg = c.clone(), d = solve(tg);
    for (let it = 0; it < 2; it++) { let x0 = 9, x1 = -9, y0 = 9, y1 = -9; cs.forEach(p => { const q = p.clone().project(cam_); x0 = Math.min(x0, q.x); x1 = Math.max(x1, q.x); y0 = Math.min(y0, q.y); y1 = Math.max(y1, q.y); });
      const cx = (x0 + x1) / 2, cy = (y0 + y1) / 2, hh = Math.tan(cam_.fov * Math.PI / 360) * d, right = V(1, 0, 0).applyQuaternion(cam_.quaternion), up = V(0, 1, 0).applyQuaternion(cam_.quaternion); tg.addScaledVector(right, cx * hh * aspect).addScaledVector(up, cy * hh); d = solve(tg); }
  }
  function snap(w, h, bgTop, bgBot) {
    const r = ctx.renderer, size = r.getSize(V(0, 0, 0)), pr = r.getPixelRatio(), vp = r.getViewport(new T.Vector4()), clips = r.clippingPlanes; r.clippingPlanes = []; r.setScissorTest(false); r.setPixelRatio(1); r.setSize(w, h, false); r.setViewport(0, 0, w, h); cam.aspect = w / h; cam.updateProjectionMatrix(); r.autoClear = true; r.render(gs, cam);
    const c = document.createElement('canvas'); c.width = w; c.height = h; const x = c.getContext('2d'), g = x.createLinearGradient(0, 0, 0, h); g.addColorStop(0, bgTop || '#ffffff'); g.addColorStop(1, bgBot || '#e6eaf0'); x.fillStyle = g; x.fillRect(0, 0, w, h); x.drawImage(r.domElement, 0, 0, w, h);
    r.setPixelRatio(pr); r.setSize(size.x, size.y, false); r.setViewport(vp); r.clippingPlanes = clips; ctx.S.need = true; return c;
  }
  const proj = (p, w, h) => { const v = p.clone().project(cam); return [(v.x * .5 + .5) * w, (-v.y * .5 + .5) * h, v.z]; };
  function pill(ctx2, text, px, py, col, fs) {
    ctx2.font = `bold ${fs}px system-ui,Segoe UI,sans-serif`; const w = ctx2.measureText(text).width + fs, h = fs * 1.7, rr = h / 2.4; ctx2.fillStyle = col || '#1b2430'; ctx2.strokeStyle = '#fff'; ctx2.lineWidth = Math.max(2, fs * .12); ctx2.beginPath(); ctx2.moveTo(px + rr, py); ctx2.arcTo(px + w, py, px + w, py + h, rr); ctx2.arcTo(px + w, py + h, px, py + h, rr); ctx2.arcTo(px, py + h, px, py, rr); ctx2.arcTo(px, py, px + w, py, rr); ctx2.closePath(); ctx2.fill(); ctx2.stroke(); ctx2.fillStyle = '#fff'; ctx2.textBaseline = 'middle'; ctx2.fillText(text, px + fs / 2, py + h / 2 + 1); return { w, h };
  }
  function labels(canvas, items, fs) {
    const x = canvas.getContext('2d'), W = canvas.width, H = canvas.height; items = items.filter(i => i.p[2] < 1).sort((a, b) => a.p[1] - b.p[1]); const Ls = [], Rs = []; items.forEach(it => (it.p[0] < W / 2 ? Ls : Rs).push(it));
    const place = (arr, side) => { let lastY = -999; arr.forEach(it => { x.font = `bold ${fs}px system-ui,sans-serif`; const w = x.measureText(it.text).width + fs, h = fs * 1.7; let y = Math.max(8, Math.min(H - h - 8, it.p[1] - h / 2)); if (y < lastY + h + 8) y = lastY + h + 8; lastY = y; const px = side === 0 ? 12 : W - w - 12;
      x.strokeStyle = '#1b2430'; x.lineWidth = Math.max(2.5, fs * .13); x.beginPath(); x.moveTo(side === 0 ? px + w : px, y + h / 2); x.lineTo(it.p[0], it.p[1]); x.stroke(); x.fillStyle = '#ffd400'; x.beginPath(); x.arc(it.p[0], it.p[1], fs * .38, 0, 7); x.fill(); x.stroke(); pill(x, it.text, px, y, it.col, fs); }); }; place(Ls, 0); place(Rs, 1);
  }
  function arrow(x, a, b, col, k) {
    const dx = b[0] - a[0], dy = b[1] - a[1], len = Math.hypot(dx, dy); if (len < 22 * k) return; const ux = dx / len, uy = dy / len, hw = 17 * k, hl = 34 * k, e = [b[0] - ux * 8 * k, b[1] - uy * 8 * k];
    x.save(); x.lineCap = 'round'; x.lineJoin = 'round'; [['#1b2430', 16 * k, 1.35], [col || '#ffd400', 9.5 * k, 1]].forEach(([c, w, m]) => { x.strokeStyle = c; x.fillStyle = c; x.lineWidth = w; x.beginPath(); x.moveTo(a[0], a[1]); x.lineTo(e[0] - ux * hl, e[1] - uy * hl); x.stroke(); x.beginPath(); x.moveTo(e[0], e[1]); x.lineTo(e[0] - ux * hl - uy * hw * m, e[1] - uy * hl + ux * hw * m); x.lineTo(e[0] - ux * hl + uy * hw * m, e[1] - uy * hl - ux * hw * m); x.closePath(); x.fill(); }); x.restore();
  }
  const tbox = (def, m) => ctx.geomOf(def).boundingBox.clone().applyMatrix4(m);
  const exVec = (i, f) => V(...(i.ex || [0, 0, 0])).multiplyScalar(f);
  const instMat = (i, off) => new T.Matrix4().makeTranslation(off.x, off.y, off.z).multiply(i.m);
  function shadowDisc(box) {
    const c = document.createElement('canvas'); c.width = c.height = 256; const x = c.getContext('2d'), g = x.createRadialGradient(128, 128, 10, 128, 128, 126); g.addColorStop(0, 'rgba(40,30,20,.34)'); g.addColorStop(.55, 'rgba(40,30,20,.14)'); g.addColorStop(1, 'rgba(40,30,20,0)'); x.fillStyle = g; x.fillRect(0, 0, 256, 256);
    const sz = box.getSize(V(0, 0, 0)), m = new T.Mesh(new T.PlaneGeometry(sz.x * 1.5, sz.y * 2.1), new T.MeshBasicMaterial({ map: new T.CanvasTexture(c), transparent: true, depthWrite: false })); m.position.set((box.min.x + box.max.x) / 2, (box.min.y + box.max.y) / 2, Math.max(0, box.min.z) + .3); gs.add(m);
  }
  function addAll(M, maxStep, newStep, exf) {
    clear(); const box = new T.Box3(), news = []; M.insts.forEach(i => { if (i.step > maxStep) return; const isNew = newStep !== null && i.step === newStep, off = isNew ? exVec(i, exf) : V(0, 0, 0), def = M.defs.get(i.def); addInst(def, instMat(i, off), isNew ? 'new' : 'real'); box.union(tbox(def, instMat(i, off))); box.union(tbox(def, i.m)); if (isNew) news.push({ i, off, def }); }); return { box, news };
  }
  function heroAsm(st) {
    const M = S.M, [w, h] = SZ3, k = w / 1000, { box, news } = addAll(M, st.asm, st.asm, st.exf || .5), fl = new T.Box3(); M.insts.forEach(i => { if (i.step <= st.asm) fl.union(tbox(M.defs.get(i.def), i.m)); }); shadowDisc(fl);
    frame(cam, box, st.dir || [.7, -.9, .6], .9, w / h); const c = snap(w, h), x = c.getContext('2d'), seen = new Set(); let na = 0;
    news.forEach(({ i, off, def }) => { if (seen.has(i.def) || na >= 8) return; seen.add(i.def); const cc = tbox(def, instMat(i, off)).getCenter(V(0, 0, 0)); if (off.length() > 10) { arrow(x, proj(cc, w, h), proj(cc.clone().sub(off), w, h), null, k); na++; } });
    let detail = null; if (st.detail && news.length) { const pick = st.detail === 'first' ? news[0] : news[st.detail]; const bb = tbox(pick.def, instMat(pick.i, pick.off)).union(tbox(pick.def, pick.i.m)); const home = tbox(pick.def, pick.i.m), cen = home.getCenter(V(0, 0, 0)); const bx = new T.Box3().setFromCenterAndSize(cen, V(150, 150, 150)); bx.union(bb); frame(cam, bx, st.dir || [.7, -.9, .6], .8, SZD[0] / SZD[1]); detail = snap(SZD[0], SZD[1]); const xd = detail.getContext('2d'); const cc = bb.getCenter(V(0, 0, 0)); arrow(xd, proj(cc, SZD[0], SZD[1]), proj(cc.clone().sub(pick.off), SZD[0], SZD[1]), null, SZD[0] / 1000); }
    return { hero: c, detail };
  }
  function heroSubset(st) {
    const M = S.M, [w, h] = SZ3, k = w / 1000, box = new T.Box3(), arrows = [], feats = []; clear();
    st.show.forEach(s => { const i = M.insts.filter(q => q.def === s.def)[s.idx - 1]; if (!i) return; const off = V(...s.ex), def = M.defs.get(i.def); addInst(def, instMat(i, off), s.ex.some(v => v) ? 'new' : 'real'); box.union(tbox(def, instMat(i, off))); box.union(tbox(def, i.m)); if (st.tags) featBoxes(def, instMat(i, off), st.tags).forEach(f => feats.push(f)); if (off.length() > 10) { const cc = tbox(def, instMat(i, off)).getCenter(V(0, 0, 0)); arrows.push([cc, cc.clone().sub(off)]); } });
    frame(cam, box, st.dir, .88, w / h); const c = snap(w, h), x = c.getContext('2d'); arrows.slice(0, 6).forEach(([a, b]) => arrow(x, proj(a, w, h), proj(b, w, h), null, k));
    if (feats.length) { const its = []; feats.forEach(f => { if (f.f.label) its.push({ p: proj(f.c, w, h), text: f.f.label, col: f.f.kind === 'cut' ? '#b34700' : '#0b6b2e' }); }); labels(c, dedupe(its).slice(0, 4), Math.round(w * .021)); } return { hero: c };
  }
  function heroPart(st) {
    const M = S.M, [w, h] = SZ3, k = w / 1000; clear(); let ox = 0; const feats = [], box = new T.Box3();
    st.focus.forEach(id => { const def = M.defs.get(id), b = def.box, m = new T.Matrix4().makeTranslation(ox - b[0], -(b[1] + b[4]) / 2, -b[2]); addInst(def, m, 'real'); box.union(tbox(def, m)); featBoxes(def, m, st.tags).forEach(f => feats.push(Object.assign(f, { def }))); ox += b[3] - b[0] + 70; });
    frame(cam, box, st.dir || [.8, -.85, .6], .9, w / h); const c = snap(w, h), x = c.getContext('2d'), seen = {}, items = [];
    feats.forEach(f => { if (!f.f.label) return; const key = f.def.id + f.f.tag + f.f.label; if (seen[key]) return; seen[key] = 1; items.push({ p: proj(f.c, w, h), text: f.f.label, col: f.f.kind === 'cut' ? '#b34700' : '#0b6b2e' }); }); labels(c, items.slice(0, 6), Math.round(w * .021));
    let detail = null; if (st.zoom) { const base = feats.filter(f => st.tags.includes(f.f.tag)); if (base.length) { const first = base[0], rad = typeof st.zoom === 'number' ? Math.min(st.zoom, 260) : 95, near = base.filter(f => f.c.distanceTo(first.c) < rad), bb = new T.Box3(); near.forEach(f => { const hs = V(f.size[0], f.size[1], f.size[2]).multiplyScalar(.5); bb.expandByPoint(f.c.clone().add(hs)); bb.expandByPoint(f.c.clone().sub(hs)); }); const cen = bb.getCenter(V(0, 0, 0)), box2 = new T.Box3().setFromCenterAndSize(cen, V(1, 1, 1).multiplyScalar(Math.max(70, bb.getSize(V(0, 0, 0)).length() * 1.2))); frame(cam, box2, st.dir || [.8, -.85, .6], .78, SZD[0] / SZD[1]); detail = snap(SZD[0], SZD[1]); const its = near.filter(f => f.f.label).map(f => ({ p: proj(f.c, SZD[0], SZD[1]), text: f.f.label, col: f.f.kind === 'cut' ? '#b34700' : '#0b6b2e' })); labels(detail, dedupe(its).slice(0, 3), Math.round(SZD[0] * .034)); } }
    return { hero: c, detail };
  }
  const dedupe = a => { const s = new Set(); return a.filter(i => !s.has(i.text) && s.add(i.text)); };
  function heroFlat() {
    const M = S.M, [w, h] = SZF; clear(); const defs = [...M.defs.values()].sort((a, b) => CAD.GROUPS.findIndex(g => g.id === a.grp) - CAD.GROUPS.findIndex(g => g.id === b.grp)); const items = defs.map(d => { const om = orientM(d.size), s = d.size.slice().sort((a, b) => b - a); return { d, om, w: s[0], h: s[1] }; });
    const W = 2300, gap = 90; let x = 0, y = 0, rowH = 0; items.forEach(it => { if (x + it.w > W) { x = 0; y += rowH + gap; rowH = 0; } it.x = x; it.y = y; x += it.w + gap; rowH = Math.max(rowH, it.h); });
    const box = new T.Box3(), labs = []; items.forEach(it => { const b = it.d.box, c = V((b[0] + b[3]) / 2, (b[1] + b[4]) / 2, b[2]), m = new T.Matrix4().makeTranslation(it.x + it.w / 2, it.y + it.h / 2, 0).multiply(it.om).multiply(new T.Matrix4().makeTranslation(-c.x, -c.y, -c.z)); addInst(it.d, m, 'real'); const bb = tbox(it.d, m); box.union(bb); labs.push({ it, c: bb.getCenter(V(0, 0, 0)) }); });
    const g = new T.Mesh(new T.PlaneGeometry(12000, 12000), new T.MeshBasicMaterial({ color: 0xf1ede6 })); g.position.set(0, 0, -1); gs.add(g);
    frame(cam, box, [0, -.12, 1], .93, w / h); const c = snap(w, h, '#f6f3ee', '#ece7de'), xx = c.getContext('2d'), fs = Math.round(w * .0105); const rects = []; labs.forEach(l => { const t = l.it.d.name.replace(/\s*\(.*\)/g, '').replace('Carcass ', '').replace(' 44 × 44', '').slice(0, 34) + '  ×' + l.it.d.qty; xx.font = `bold ${fs}px system-ui,sans-serif`; const p = proj(l.c, w, h), tw = xx.measureText(t).width + fs, th = fs * 1.6; let rx = p[0] - tw / 2, ry = p[1] - th / 2; for (let it = 0; it < 14; it++) { const hit = rects.find(r => rx < r.x + r.w + 4 && r.x < rx + tw + 4 && ry < r.y + r.h + 3 && r.y < ry + th + 3); if (!hit) break; ry = hit.y + hit.h + 4; } rects.push({ x: rx, y: ry, w: tw, h: th }); if (Math.abs(ry - (p[1] - th / 2)) > th) { xx.strokeStyle = '#1b2430'; xx.lineWidth = 2; xx.beginPath(); xx.moveTo(p[0], p[1]); xx.lineTo(rx + tw / 2, ry + th / 2); xx.stroke(); xx.fillStyle = '#ffd400'; xx.beginPath(); xx.arc(p[0], p[1], fs * .3, 0, 7); xx.fill(); xx.stroke(); } xx.fillStyle = 'rgba(27,36,48,.92)'; xx.fillRect(rx, ry, tw, th); xx.fillStyle = '#fff'; xx.textBaseline = 'middle'; xx.fillText(t, rx + fs / 2, ry + th / 2); }); return { hero: c };
  }
  function heroAll() { const M = S.M, [w, h] = SZF; clear(); const box = new T.Box3(); M.insts.forEach(i => { const d = M.defs.get(i.def); addInst(d, i.m, 'real'); box.union(tbox(d, i.m)); }); shadowDisc(box); frame(cam, box, [.7, -1, .5], .8, w / h); return { hero: snap(w, h, '#ffffff', '#eceff4') }; }
  function thumb(id) {
    if (thumbs[id]) return thumbs[id]; const M = S.M, def = M.defs.get(id); clear(); const b = def.box, m = new T.Matrix4().makeTranslation(-(b[0] + b[3]) / 2, -(b[1] + b[4]) / 2, -(b[2] + b[5]) / 2); addInst(def, m, 'real'); const box = tbox(def, m), sz = def.size, long = sz.indexOf(Math.max(...sz)), dir = long === 2 ? [.9, -1, .45] : long === 0 ? [.45, -1, .8] : [1, -.45, .8]; frame(cam, box, dir, .9, 260 / 180); return thumbs[id] = snap(260, 180, '#ffffff', '#ffffff').toDataURL('image/jpeg', .9);
  }
  /* ----- pages ----- */
  const css = document.querySelector('style').textContent; // reuse page css from the template
  function partsFor(st) {
    let list = st.parts; if (!list && st.kind === 'asm') { const m = {}; S.M.insts.forEach(i => { if (i.step === st.asm) m[i.def] = (m[i.def] || 0) + 1; }); list = Object.entries(m).map(([def, qty]) => ({ def, qty })); }
    if (!list && st.kind === 'subset') { const m = {}; st.show.forEach(s => m[s.def] = (m[s.def] || 0) + 1); list = Object.entries(m).map(([def, qty]) => ({ def, qty })); } return (list || []).slice(0, 5);
  }
  function pageHTML(st, i, total, imgs) {
    const full = st.kind === 'hero' || st.kind === 'flat' || st.kind === 'text' || st.kind === 'cutlist'; const parts = full ? '' : `<div class="parts"><h4>Parts needed</h4>${partsFor(st).map(p => `<div class="pt"><img src="${imgs.thumbs[p.def]}"><b>${p.qty}×</b><span>${S.M.defs.get(p.def).name.replace(/\(.*\)/, '')}</span></div>`).join('')}</div>`;
    let body = ''; if (st.kind === 'cutlist') body = cutTable(); else if (st.kind !== 'text') body = `<div class="hero"><img class="m" src="${imgs.hero}">${imgs.detail ? `<div class="inset"><i>DETAIL</i><img src="${imgs.detail}"></div>` : ''}</div>`; else body = `<div class="hero" style="background:#fffbea"><div style="padding:18px 26px;font-size:15px;line-height:1.45">${st.text.map(t => `<p style="margin:0 0 12px">${t}</p>`).join('')}</div></div>`;
    const side = st.kind === 'text' || st.kind === 'cutlist' ? '' : `<div class="side"><ol>${st.text.map(t => `<li>${t}</li>`).join('')}</ol>${st.tools && st.tools.length ? `<div class="tools"><b>Tools</b>${st.tools.join(' · ')}</div>` : ''}${st.tip ? `<div class="tip"><b>TIP</b> ${st.tip}</div>` : ''}${st.chk ? `<div class="chk"><b>CHECK</b> ${st.chk}</div>` : ''}</div>`;
    const cls = 'pg' + (parts ? '' : ' full'); const wide = st.kind === 'cutlist' || st.kind === 'text';
    return `<section class="${cls}" ${wide ? 'style="grid-template-columns:1fr"' : ''}><div class="hd"><div class="badge">${st.n}</div><div><div class="ph">${st.phase}</div><h2>${st.title}</h2></div></div>${parts}${body}${side}<div class="ft"><span>Walnut sideboard · build guide</span><div class="bar"><i style="width:${(i + 1) / total * 100}%"></i></div><span>${i + 1} / ${total}</span></div></section>`;
  }
  function buyList() {
    const L = S.M.L, ply = ['back_panel', 'drawer_bottom'], wood = CAD.cutList(S.M).filter(r => !ply.includes(r.id) && r.id !== 'marble'), vol = wood.reduce((a, r) => a + r.vol * r.qty, 0) / 1e6;
    return `<div style="margin-top:10px;border:2px dashed #6b7788;border-radius:10px;padding:8px 12px;font-size:12px;line-height:1.45"><b>STOCK TO BUY</b> (allowing 3 mm milling + 25 % waste)<br>• <b>Walnut 8/4:</b> four legs, 50 × 50 × ${L.Hl + 30} mm each, plus the four 50 × 50 apron stock if you prefer solid blanks.<br>• <b>Walnut 5/4:</b> ≈ ${(vol * .62 * 1.25).toFixed(0)} dm³ for panels, divider, rails, stretchers and drawer fronts.<br>• <b>Walnut 4/4:</b> ≈ ${(vol * .38 * 1.25).toFixed(0)} dm³ for drawer sides/backs, door stiles, rails and ${S.M.defs.get('door_slat').qty} slats, pegs and keys.<br>• <b>6 mm walnut-veneer ply:</b> one 1.4 × 0.5 m offcut for the back panel and four drawer bottoms. • <b>Marble:</b> ${L.W} × ${L.D} × 20 mm slab, 4 blind Ø12-square sockets.</div>`;
  }
  function cutTable() {
    const rows = CAD.cutList(S.M).sort((a, b) => CAD.GROUPS.findIndex(g => g.id === a.grp) - CAD.GROUPS.findIndex(g => g.id === b.grp)); const half = Math.ceil(rows.length / 2), t = rs => `<table><tr><th>Part</th><th>Qty</th><th>T×W×L (mm)</th></tr>${rs.map(r => `<tr><td>${r.name.replace(/\(.*\)/, '')}</td><td>${r.qty}</td><td>${N(r.T)} × ${N(r.W)} × ${N(r.L)}</td></tr>`).join('')}</table>`;
    return `<div class="hero" style="background:#fff;display:block;padding:8px 14px"><div style="display:grid;grid-template-columns:1fr 1fr;gap:18px">${t(rows.slice(0, half))}${t(rows.slice(half))}</div><p style="font-size:11px;margin:8px 0 0;color:#445">Finished sizes. Mill each part ~3 mm over in every dimension, then cut joints. Walnut except back panel and drawer bottoms (6 mm ply) and the marble top. Pegs and keys: offcuts. Total wood ≈ ${(rows.reduce((s, r) => s + r.vol * r.qty, 0) / 1e6).toFixed(1)} dm³.</p>${buyList()}</div>`;
  }
  async function generate(cb) {
    steps = CAD.guideSteps(S.M); pages = []; thumbs = {}; const imgs = []; const tick = () => new Promise(r => setTimeout(r, 0));
    for (let i = 0; i < steps.length; i++) {
      const st = steps[i]; cb && cb(i, steps.length); await tick(); let r = {}, th = {};
      if (st.kind === 'hero') r = { hero: heroAll().hero }; else if (st.kind === 'flat') r = heroFlat(); else if (st.kind === 'asm') r = heroAsm(st); else if (st.kind === 'subset') r = heroSubset(st); else if (st.kind === 'part') r = heroPart(st);
      const out = { hero: r.hero ? r.hero.toDataURL('image/jpeg', .88) : null, detail: r.detail ? r.detail.toDataURL('image/jpeg', .88) : null, thumbs: {} };
      if (!['hero', 'flat', 'text', 'cutlist'].includes(st.kind)) partsFor(st).forEach(p => { out.thumbs[p.def] = thumb(p.def); });
      imgs.push(out); pages.push(pageHTML(st, i, steps.length, out));
    } clear(); return pages.length;
  }
  const el = { box: () => $('#guide'), body: () => $('#gbody'), sel: () => $('#gsel') };
  function show(i) { cur = Math.max(0, Math.min(pages.length - 1, i)); el.body().innerHTML = pages[cur]; el.body().parentNode.dataset.mode = 'one'; el.sel().value = cur; $('#gprog').textContent = `step ${cur + 1} of ${pages.length}`; el.body().scrollTop = 0; }
  function showAll() { el.body().innerHTML = '<div style="display:flex;flex-direction:column;gap:18px;width:100%;align-items:center">' + pages.join('') + '</div>'; }
  async function open() {
    el.box().style.display = 'flex'; if (!pages) { el.body().innerHTML = '<div style="padding:40px;color:#445;font:16px system-ui">Rendering the guide from the live model… <b id="gp">0%</b></div>'; await generate((i, n) => { const p = $('#gp'); if (p) p.textContent = Math.round(i / n * 100) + '%  (step ' + (i + 1) + ' of ' + n + ')'; }); el.sel().innerHTML = steps.map((s, i) => `<option value="${i}">${s.n}. ${s.title}</option>`).join(''); } show(cur);
  }
  function invalidate() { pages = null; }
  function standalone() { return `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>Walnut sideboard — build guide</title><style>${css}\nbody{overflow:auto!important;background:#eef1f5;height:auto!important}#guide{display:block!important;position:static!important}#gbody{display:flex;flex-direction:column;gap:18px;align-items:center;padding:18px}.pg{width:min(1180px,96vw)}</style></head><body><div id="guide"><div class="gb" id="gbody">${pages.join('')}</div></div></body></html>`; }
  async function save() { if (!pages) await generate(); const html = standalone(); return ctx.deliver('sideboard_build_guide', [{ name: 'sideboard_build_guide.html', data: html }]); }
  $('#gclose').onclick = () => { el.box().style.display = 'none'; ctx.S.need = true; }; $('#gprev').onclick = () => show(cur - 1); $('#gnext').onclick = () => show(cur + 1); $('#gsel').onchange = e => show(+e.target.value); $('#gall').onclick = () => { if (pages) showAll(); }; $('#gprint').onclick = () => { if (pages) { showAll(); setTimeout(() => window.print(), 100); } }; $('#gsave').onclick = save;
  addEventListener('keydown', e => { if (el.box().style.display !== 'flex') return; if (e.key === 'ArrowRight') show(cur + 1); else if (e.key === 'ArrowLeft') show(cur - 1); else if (e.key === 'Escape') $('#gclose').click(); });
  return { open, save, generate, show, showAll, invalidate, steps: () => steps, pages: () => pages, standalone };
};
})(typeof globalThis !== 'undefined' ? globalThis : window);
