// End-to-end UI test of the AI path with a FAKE Anthropic endpoint (no key needed). node tests/browser-ai.mjs
import chromium from '@sparticuz/chromium'; import puppeteer from 'puppeteer-core'; import fs from 'fs'; import path from 'path'; import { fileURLToPath } from 'url';
const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..'), out = path.join(root, 'tests/out'); fs.mkdirSync(out, { recursive: true });
const good = JSON.parse(fs.readFileSync(path.join(root, 'examples/bookshelf.json'), 'utf8')); const bad = JSON.parse(JSON.stringify(good)); bad.parts.find(p => p.id === 'divider').ops[0].add[3] = 40; // divider now overlaps the drawers
const replies = [JSON.stringify(bad), 'Fixed:\n```json\n' + JSON.stringify(good) + '\n```']; const seen = []; let fails = 0; const check = (c, m) => { console.log((c ? '  ✓ ' : '  ✗ ') + m); if (!c) fails++; };
const browser = await puppeteer.launch({ executablePath: await chromium.executablePath(), args: [...chromium.args, '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist', '--no-sandbox'], headless: 'shell', defaultViewport: { width: 1500, height: 900 } });
const page = await browser.newPage(), errs = []; page.on('console', m => { if (m.type() === 'error' && !/Failed to load resource/.test(m.text())) errs.push(m.text()); }); page.on('pageerror', e => errs.push('PAGEERROR ' + e.message)); page.on('dialog', d => { errs.push('DIALOG ' + d.message()); d.dismiss(); });
await page.setRequestInterception(true); const cors = { 'access-control-allow-origin': '*', 'access-control-allow-headers': '*', 'access-control-allow-methods': '*' };
page.on('request', r => { const u = r.url(), nm = path.join(root, 'node_modules/three');
  if (u.startsWith('https://api.anthropic.com/v1/messages')) { if (r.method() === 'OPTIONS') return r.respond({ status: 204, headers: cors }); seen.push({ headers: r.headers(), body: JSON.parse(r.postData()) }); return r.respond({ status: 200, headers: cors, contentType: 'application/json', body: JSON.stringify({ content: [{ type: 'text', text: replies[Math.min(seen.length - 1, replies.length - 1)] }] }) }); }
  if (u.includes('three.min.js')) return r.respond({ status: 200, contentType: 'application/javascript', body: fs.readFileSync(nm + '/build/three.min.js') }); if (u.includes('OrbitControls.js')) return r.respond({ status: 200, contentType: 'application/javascript', body: fs.readFileSync(nm + '/examples/js/controls/OrbitControls.js') }); if (u.startsWith('file:')) return r.continue(); r.abort(); });
await page.goto('file://' + path.join(root, 'dist/image-to-cad.html')); await page.waitForFunction(() => window.__cad && document.getElementById('loading').style.display === 'none', { timeout: 120000 }); await new Promise(r => setTimeout(r, 1000));
console.log('AI tab, real provider code path');
await page.click('#bAI'); await page.evaluate(async () => { const c = document.createElement('canvas'); c.width = 800; c.height = 600; const x = c.getContext('2d'); x.fillStyle = '#c9a77c'; x.fillRect(0, 0, 800, 600); x.fillStyle = '#222'; x.fillRect(150, 100, 500, 400); const blob = await new Promise(r => c.toBlob(r, 'image/png')); await __cad.setImage(new File([blob], 'shelf.png', { type: 'image/png' })); });
await page.type('#aiKey', 'sk-ant-TEST'); await page.type('#aiHints', 'height 1800 mm, oak'); await page.select('#aiRounds', '3'); await page.click('#aiGo');
await page.waitForFunction(() => /Done:|Stopped after|Error/.test(document.getElementById('aiLog').innerText), { timeout: 60000 }); await new Promise(r => setTimeout(r, 800));
const log = await page.evaluate(() => document.getElementById('aiLog').innerText), name = await page.evaluate(() => __cad.S.M.meta.name);
check(seen.length === 2, 'two model calls (draft + critic-driven fix): ' + seen.length); check(/passes every check/.test(log), 'loop reports success'); check(name === 'Bookshelf with drawers', 'final design is loaded in the viewer: ' + name);
const r0 = seen[0]; check(r0.headers['x-api-key'] === 'sk-ant-TEST' && r0.headers['anthropic-version'] === '2023-06-01' && r0.headers['anthropic-dangerous-direct-browser-access'] === 'true', 'API headers correct'); check(r0.body.model === 'claude-sonnet-4-5' && r0.body.max_tokens > 8000, 'model and max_tokens sent');
const c0 = r0.body.messages[0].content; check(c0[0].type === 'image' && c0[0].source.type === 'base64' && c0[0].source.media_type === 'image/jpeg' && c0[0].source.data.length > 100, 'picture sent as a base64 image block'); check(c0[c0.length - 1].type === 'text' && /height 1800 mm, oak/.test(c0[c0.length - 1].text) && /DESIGN SPEC/.test(c0[c0.length - 1].text), 'prompt carries the brief and the spec language');
const t1 = seen[1].body.messages[0].content.slice(-1)[0].text; check(/CRITIC REPORT/.test(t1) && /INTERFERENCE/.test(t1) && /divider/.test(t1) && /PREVIOUS SPEC/.test(t1), 'critic findings reach the model in round 2');
await page.screenshot({ path: path.join(out, 'ai.png') });
console.log('Spec tab'); await page.click('[data-t=spec]');
await page.evaluate(() => { const t = document.getElementById('specTxt'); const s = JSON.parse(t.value); s.parts[0].ops[0].add[5] = 'nope+1'; t.value = JSON.stringify(s); document.getElementById('spApply').click(); }); await new Promise(r => setTimeout(r, 300));
check(await page.evaluate(() => /unknown variable "nope"/.test(document.getElementById('specErr').innerText) && __cad.S.M.meta.name === 'Bookshelf with drawers'), 'bad edit shows a path-qualified error and keeps the previous model');
await page.evaluate(() => { const t = document.getElementById('specTxt'); const s = JSON.parse(t.value); s.parts[0].ops[0].add[5] = 'H'; s.params.W.value = 1200; t.value = JSON.stringify(s); document.getElementById('spApply').click(); }); await new Promise(r => setTimeout(r, 600));
check(await page.evaluate(() => Math.round(__cad.S.M.size[0]) === 1200), 'valid edit rebuilds at the new width');
console.log('Design tab (parameter slider)'); await page.click('[data-t=param]'); await page.evaluate(() => { const e = document.getElementById('pp3'); e.value = 6; e.dispatchEvent(new Event('change')); }); await new Promise(r => setTimeout(r, 900));
check(await page.evaluate(() => __cad.S.M.defs.get('board') && __cad.S.M.insts.filter(i => i.def === 'board').length === 8), 'shelf-count slider re-cuts the model (6 shelves + top + bottom)');
console.log('Security: hostile spec text must not execute'); const evil = { name: '<img src=x onerror="window.__xss=1">', description: '<script>window.__xss=2<\/script>', params: {}, groups: [{ id: 'g', name: '<b onmouseover="window.__xss=3">G</b>' }], steps: ['<img src=x onerror="window.__xss=4">'], parts: [{ id: 'p', name: '<img src=x onerror="window.__xss=5">', group: 'g', notes: ['<img src=x onerror="window.__xss=6">'], spec: '<i>', ops: [{ add: [0, 0, 0, 100, 100, 100], tag: 't', label: '<img src=x onerror="window.__xss=7">' }, { cut: [10, 10, 10, 20, 20, 20], tag: 'm', fill: true, label: '<img src=x onerror="window.__xss=8">' }], instances: [{ pos: [0, 0, 0] }] }] };
await page.evaluate(spec => { __cad.loadSpec(spec, {}); }, evil); await page.click('[data-t=insp]'); await page.evaluate(() => { __cad.selectDef('p'); }); await new Promise(r => setTimeout(r, 400)); await page.evaluate(() => { document.querySelector('.pr') && document.querySelector('.pr').click(); __cad.showCut(); }); await page.click('#mclose').catch(() => { });
await page.evaluate(async () => { await window.__guide.generate(() => { }); document.getElementById('guide').style.display = 'flex'; window.__guide.showAll(); }); await new Promise(r => setTimeout(r, 700));
check(await page.evaluate(() => window.__xss === undefined && !document.querySelector('img[onerror]') && !document.querySelector('[onmouseover]')), 'no injected script, handler or element survives in tree, inspector, cut list or guide');
console.log('console errors:', errs); fails += errs.length; await browser.close(); console.log(fails ? '\n' + fails + ' FAILED' : '\nall UI checks passed'); process.exit(fails ? 1 : 0);
